### ISSUE TITLE
There is some problem in encoding

### ISSUE THREAD

**Issue by Antarix** [gregko/WebArchiveReader#1]
i saved one webpage e.g http://m.sme.sk , and when i tried to read this saved xml it shows some unusual characters especially with other languages like arabic, hindi etc...

**Comment by gregko** [comment]
Antarix, could you try adding the following 2 lines to loadToWebView() function, before line 95 which says:

v.LoadDataWithBaseUrl(...);

Add this:

```
            WebSettings settings = v.getSettings();
            settings.setDefaultTextEncodingName("UTF-8");
```

Please test it and let me know if it works correctly then. If not, I'd like to get a copy of your archive to test it myself, the original URL address of this page, and maybe you could highlight on your image a few of wrong characters and tell me what they should be correctly, as I'm not that familiar with the language (Slovak? I can understand most of it, being Polish by origin, but don't know the correct spelling).

Greg

**Comment by Antarix** [comment]
I tried your logic but no success. Here is the original link http://www.sme.sk/ ,unfortunately I am also not familiar with  this language but you can compare any word with original site. The problem arise when we try to read any saved webpage that has language other than English. Can you please give me your mail Id so that i can send you my archive file

attaching screen shots here

![screenshot_2013-07-17-09-15-28](https://f.cloud.github.com/assets/1435726/809678/4832a67c-ee94-11e2-806f-56878f8a97eb.png)
![screenshot_2013-07-17-09-15-08](https://f.cloud.github.com/assets/1435726/809679/48d129aa-ee94-11e2-888a-7297cf847aa8.png)

But i am very thankful to you for reply me :) hope you could give us a solution

**Comment by gregko** [comment]
When I look at the image you provided in the 1st post, and now at the page http://www.sme.sk/, I see that characters match correctly, but don't know if this is the same you see in your Android app. My email is gregko AT hyperionics DOT com. Please send me your saved archive, and also tell me how you created this archive, the exact code to create it, and under which version of Android (or other system) you did this?

Greg

**Comment by Antarix** [comment]
Thanks Greg :+1:
