### ISSUE TITLE
Encoding problem for mobile sites

### ISSUE THREAD

**Issue by sendtomitesh** [gregko/WebArchiveReader#2]
Hi greg,
       I am team mate with antarix, Continuing issue closed yesterday only, I can see that, it encode weburl properly (http://www.sme.sk) but not the mobile site url(http://m.sme.sk).
Look at this issue. It will be a great help to me, as i m using this in a big forthcomming android app. Attached is the screenshot of wrong encoding. 
You can also email me at sendtomitesh At gmail Dot com  

Thanks in advance.
![screenshot_2013-07-19-20-50-07](https://f.cloud.github.com/assets/1181169/829661/4eeaf42c-f0f3-11e2-8f4c-952588563a65.png)

**Comment by gregko** [comment]
I tested this page (m.sme.sk) with my latest code, posted now also on GitHub, and it works correctly. As I wrote to Antarix yesterday, I added charset encoding detection code from IBM’s ICU4J library and use it for pages that don’t have meta tag specifying the encoding. Talk to Antarix about it, or just get the latest code from GitHub and test this page again.

Greg

**Comment by sendtomitesh** [comment]
hi Greg,
         I have implemented as per your suggestions and it seems working fine now.

Thanks for your Great help.
:+1:

**Comment by gregko** [comment]
OK, @sendtomitesh, good luck with your project!
